### ISSUE TITLE
Error fetching translation status

### ISSUE THREAD

**Issue by andresgarza** [onesky/plugin-xcode#13] opened 2015-01-30 02:49 UTC
I'm still getting used to OneSky, but when I try to sync my translations (I have 2 languages: english as base and Spanish) I get the following error:

```
Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Garbage at end.) UserInfo=0x7fe2584ab320 {NSDebugDescription=Garbage at end.}
```

![error](https://cloud.githubusercontent.com/assets/154718/5970402/4dac9c10-a7f8-11e4-9ddd-1a07ff0d4cd4.png)

**Comment by bretdabaker** [comment] 2015-01-30 03:39
Thanks for reporting the bug, the error means the response from server could not be parsed as JSON, we are working out with our backend developers to solve the problem.

**Comment by bretdabaker** [comment] 2015-01-30 07:41
@andresgarza our backend developer said the problem is fixed. Could you please try again and let me know if the problem persists?

**Comment by andresgarza** [comment] 2015-01-30 16:11
@bretdabaker unfortunately, it's still happening :(

**Comment by andresgarza** [comment] 2015-01-30 16:30
It might have something specific to do with my project, as I just created an empty Xcode project and a sample OneSky project and I was able to sync strings. Perhaps a long key/id for a translation string?

**Comment by andresgarza** [comment] 2015-01-30 16:57
I used Charles to sniff out request and this is the JSON it is getting back:

```json
{
	"meta": {
		"status": 200,
		"record_count": 2
	},
	"data": [{
		"code": "en",
		"english_name": "English",
		"local_name": "English\u0000",
		"custom_locale": null,
		"locale": "en",
		"region": "",
		"is_base_language": true,
		"is_ready_to_publish": false,
		"translation_progress": "100.0%"
	}, {
		"code": "es",
		"english_name": "Spanish",
		"local_name": "Espa\u00f1ol\u0000",
		"custom_locale": null,
		"locale": "es",
		"region": "",
		"is_base_language": false,
		"is_ready_to_publish": false,
		"translation_progress": "1.0%"
	}]
}
```

**Comment by bretdabaker** [comment] 2015-02-02 03:04
@andresgarza we confirm it's a internal server error, will let you know once it's fixed on the server side.

**Comment by andresgarza** [comment] 2015-02-03 00:44
Thanks!

On Feb 1, 2015, at 9:04 PM, Bret Cheng <notifications@github.com> wrote:

@andresgarza <https://github.com/andresgarza> we confirm it's a internal
server error, will let you know once it's fixed on the server side.

—
Reply to this email directly or view it on GitHub
<https://github.com/onesky/plugin-xcode/issues/13#issuecomment-72400981>.

**Comment by andresgarza** [comment] 2015-02-05 18:51
This seems to have been fixed! Thanks!

**Closed** 2015-02-10 02:59 UTC
